### ISSUE TITLE
push_if_unclean

### ISSUE THREAD

**Issue by vittoriom** [aleclarson/dispatcher#3]
Why is there a Run Script build phase that expects there to be a  ~/scripts/push_if_unclean.sh path on the developer machine?

**Comment by aleclarson** [comment]
You must be using the **v3.0.1** branch? You can safely delete that. Sorry!

**Comment by vittoriom** [comment]
Yep, I supposed that branch was more up to date. Am I meant to use the master branch instead? By the way, very nice library :+1:

**Comment by aleclarson** [comment]
I would be careful with that branch. I've been developing locally without pushing to this repo, so it's possible there are some bugs.

Eventually I'll update this repo with the best version available, but I'm very busy as the sole developer in my startup, so I don't have much free time for open source right now. Thanks for your interest! :smile:
